### ISSUE TITLE
any idea why text comes out thinner/taller than the image?

### ISSUE THREAD

**Issue by corysimmons** [hit9/img2txt#6]
![](https://i.imgur.com/ml2SG3i.png)

this happens on other images as well.

**Comment by hit9** [comment]
The distance between left char to right char is smaller than the line to next line.

**Comment by corysimmons** [comment]
Ah I see. With `line-height: .6` it looks alright but the letters overlap and I can't use it in shell.

Think it would be possible to stretch the image horizontally before conversion so it looks a bit less squished (doesn't have to be perfect)?

**Comment by corysimmons** [comment]
Change default `line-height` to 1ch?

ch is the width of the `0` of a font set.

![image](https://cloud.githubusercontent.com/assets/224636/13520253/c684cbd2-e1ac-11e5-8466-dc7693c9ec45.png)
